apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world
  annotations:
    networking.k8s.io/v1 : ingress-nginx
spec:
  rules:
  - host: host1.domain.ext
    http:
      paths:
      - backend:
          serviceName: hello-world
          servicePort: 80