apiVersion: v1
kind: Service
metadata:
 name: myjavaapp-svc
 annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
 labels:
    app: myjavaapp
    
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
     app:  myjavaapp
    
  