apiVersion: v1
kind: Service
metadata:
 name: myjavaapp-svc
 labels:
    app: myjavaapp

spec:
  type: NodePort
  ports:
  - port: 9000
    nodePort: 30001
    protocol: TCP
    targetPort: 8080
  selector:
     app:  myjavaapp
